# Generated by Django 5.1.7 on 2025-04-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('memory', models.TextField(max_length=500)),
                ('tags', models.JSONField(default=list)),
                ('reactions', models.JSONField(default=dict)),
            ],
        ),
    ]
