# Generated by Django 5.1.7 on 2025-04-09 05:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_memory_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
